export const ipcMainChannels = {
  redirect: "redirect",
  analyticsData: "send-analytics-data",
  detaChannel: "beta-channel",
  getCurrentVersion: "get-current-version",
  installVersion: "install-version",
  frontendError: "front error",
  dictionatyUpdate: "dictionaty-update",
  startFileWatcher: "start-file-watcher",
  startFolderWatcher: "start-folder-watcher",
  checkDropboxConnection: "check-dropbox-connection",
  stopPathWatcher: "stop-path-watcher",
  backEndError: "background error",
  loadOfflinePage: "app:load-offline-page",
  trelloLogin: "trello:login",
  jiraLogin: "jira:login",
  office365Login: "office365:login",
  azureLoginBase: "azure:login-base",
};
