export const IPC_MAIN_CHANNELS = {
  REDIRECT: "redirect",
  ANALYTICS_DATA: "send-analytics-data",
  BETA_CHANNEL: "beta-channel",
  GET_CURRENT_VERSION: "get-current-version",
  INSTALL_VERSION: "install-version",
  FRONTEND_ERROR: "front error",
  DICTIONATY_UPDATE: "dictionaty-update",
  START_FILE_WATCHER: "start-file-watcher",
  START_FOLDER_WATCHER: "start-folder-watcher",
  CHECK_DROPBOX_CONNECTION: "check-dropbox-connection",
  STOP_PATH_WATCHER: "stop-path-watcher",
  BACKEND_ERROR: "background error",
  LOAD_OFFLINE_PAGE: "app:load-offline-page",
  TRELLO_LOGIN: "trello:login",
  JIRA_LOGIN: "jira:login",
  OFFICE365_LOGIN: "office365:login",
  AZURE_LOGIN_BASE: "azure:login-base",
  WINDOW_FOCUSED: "window-focused",
  RENDER_ERROR: "render error",
  TIMETRACKER_GET_BOOKINGS: "timetracker:get-bookings",
  APP_FIND_MONTH_PROJECTS: "app:find-month-projects",
  ANY_FILE_CHANGED: "any-file-changed"
};
