export const IPC_MAIN_CHANNELS = {
  REDIRECT: "redirect",
  ANALYTICS_DATA: "send-analytics-data",
  BETA_CHANNEL: "beta-channel",
  GET_CURRENT_VERSION: "get-current-version",
  INSTALL_VERSION: "install-version",
  FRONTEND_ERROR: "front error",
  DICTIONATY_UPDATE: "dictionaty-update",
  START_FILE_WATCHER: "start-file-watcher",
  START_FOLDER_WATCHER: "start-folder-watcher",
  CHECK_DROPBOX_CONNECTION: "check-dropbox-connection",
  STOP_PATH_WATCHER: "stop-path-watcher",
  BACKEND_ERROR: "background error",
  LOAD_OFFLINE_PAGE: "app:load-offline-page",
  TRELLO_LOGIN: "trello:login",
  JIRA_LOGIN: "jira:login",
  OFFICE365_LOGIN: "office365:login",
  AZURE_LOGIN_BASE: "azure:login-base",
  WINDOW_FOCUSED: "window-focused",
  RENDER_ERROR: "render error",
  TIMETRACKER_GET_BOOKINGS: "timetracker:get-bookings",
  APP_FIND_MONTH_PROJECTS: "app:find-month-projects",
  ANY_FILE_CHANGED: "any-file-changed",
  READ_DAY_REPORT: "app:read-day-report",
  APP_FIND_QUARTER_PROJECTS: "app:find-quarter-projects",
  APP_SELECT_FOLDER: "app:select-folder",
  APP_WRITE_DAY_REPORT: "app:write-day-report",
  APP_CHECK_EXIST_REPORT: "app:check-exist-report",
  TIMETRACKER_GET_PROJECTS: "timetracker:get-projects",
  TIMETRACKER_REFRESH_USER_INFO_TOKEN: "timetracker:refresh-user-info-token",
  TIMETRACKER_LOGIN: "timetracker:login",
  OPEN_CHILD_WINDOW: "open-child-window",
  GOOGLE_SHOULD_RERENDER: "google:should-rerender",
  OFFICE365_SHOULD_RERENDER: "office365:should-rerender",
  TRELLO_SHOULD_RERENDER: "trello:should-rerender",
  TIMETRACKER_SHOULD_RERENDER: "timetracker:should-rerender",
  JIRA_SHOULD_RERENDER: "jira:should-rerender",
  CHILD_WINDOW_CLOSED: "child-window-closed",
};
