name: publish release
on:
  push:
    # # Sequence of patterns matched against refs/heads
    # branches:
    #   - main
    #   - master
    # tags:
    #   - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DEBUG: electron-builder
    # container:
    #     image: node:20.5.0
    #     # env:
    #     #   NODE_ENV: development
    #     # ports:
    #     #   - 80
    #     volumes:
    #       - ./:/app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
      - run: npm run dist
        # env:
        #   #   releaseType: release
        #   releaseType: draft

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: my-artifact
    #       path: /home/runner/work/tt-test/tt-test/app/
